[mypy]
python_version = 3.9
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
check_untyped_defs = false
disallow_untyped_defs = false

[mypy-evaluation.*]
ignore_errors = false

[mypy-analysis.*]
ignore_errors = false
